Repository ContainX/openstack4j, pull requests merged in 2018-10, with the labels that each got.

#1136 Heat service, adding support for stack abandon and adopt
  core-test/src/main/java/org/openstack4j/api/heat/StackServiceTests.java
  core-test/src/main/resources/heat/abandon.json
  core-test/src/main/resources/heat/adopt.json
  core/src/main/java/org/openstack4j/api/heat/StackService.java
  core/src/main/java/org/openstack4j/model/heat/AdoptStackData.java
  core/src/main/java/org/openstack4j/openstack/heat/domain/HeatAdoptStackData.java
  core/src/main/java/org/openstack4j/openstack/heat/domain/HeatStackAdopt.java
  core/src/main/java/org/openstack4j/openstack/heat/internal/StackServiceImpl.java
Labels: enhancement

#1142 Fix for issue #1124:openstack4j mistaken heat-cfn service as heat ser…
  core-test/src/main/java/org/openstack4j/openstack/common/ServiceTypeTest.java
  core/src/main/java/org/openstack4j/api/types/ServiceType.java
Labels: Test Cases Required, enhancement

#1149 Fix for issue #979: Disable Gateway problem
  core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSubnetUpdate.java
Labels: bug

#1082 neutron attach and detach network to agent dhcp
  core-test/src/main/java/org/openstack4j/api/network/NetworkTests.java
  core/src/main/java/org/openstack4j/api/networking/ext/AgentService.java
  core/src/main/java/org/openstack4j/openstack/networking/internal/ext/AgentServiceImpl.java
Labels: enhancement
